### ISSUE TITLE
Physics Framework Integration

### ISSUE THREAD

**Issue by fynnfluegge** [fynnfluegge/oreon-engine#15]
Dyn4j is a Java Physics Engine: http://www.dyn4j.org/

**Comment by kingburrito666** [comment]
Yes! I love the engine so far! Danke dafür!

**Comment by dentmaged** [comment]
Isn't dyn4j only 2D?

**Comment by aromanelli** [comment]
@dentmaged Per their front page, "A 100% Java 2D collision detection and physics engine."

**Comment by oreonengine** [comment]
PhysX would be the best choice I guess, I didn't know that they provide a Java wrapper, but if so, that would be awesome.

**Comment by RubenWalraevens** [comment]
I came upon this: https://github.com/flyingcatslb/physx4java

But that seems rather old and outdated. 11 years ago..

**Comment by oreonengine** [comment]
Yeah 11 years is indeed outdated :/
Ode4J or JBullet can be also good solutions, but I dont't have any experience with them
