### ISSUE TITLE
How to import it into eclipse?

### ISSUE THREAD

**Issue by Mikilis** [fynnfluegge/oreon-engine#46]
How to import it into eclipse? 

I have problem with this.

**Comment by fynnfluegge** [comment]
http://fynnfluegge.github.io/oreon-engine/_navigation/Getting_Started.html

**Comment by Mikilis** [comment]
CoreException

**Comment by viloskovic** [comment]
@Mikilis Can you give us a stacktrace?

**Comment by Mikilis** [comment]
I using Eclipse Photon.



Stacktrace:
