### ISSUE TITLE
Blueflame Games copyright

### ISSUE THREAD

**Issue by BertilBraun** [fynnfluegge/oreon-engine#48]
https://www.youtube.com/watch?v=DxI5SijDFBY

I stumbled on this video, which seems to be a direct re upload of your video claiming to be a "game engine developed by Blueflame Studios". You might want to take a look into that.

**Comment by Sodex234** [comment]
Funny, seems they even left in the window title that says "OE2.1"

**Comment by BertilBraun** [comment]
Yes he seems to have deleted it.

**Comment by fynnfluegge** [comment]
LOL xD

**Comment by Mikilis** [comment]
xd
