### ISSUE TITLE
Error, error and errors.

### ISSUE THREAD

**Issue by Mikilis** [fynnfluegge/oreon-engine#63]
I have many error, in eclipse...
![blady](https://user-images.githubusercontent.com/44727101/63776611-ff6c5f80-c8e1-11e9-9430-2c1949bacc1b.png)

**Comment by Mikilis** [comment]
(Project called "Logic Bricks" is unused)

**Comment by Mikilis** [comment]
I only restart eclipse and WORKING xDDD

**Comment by fynnfluegge** [comment]
lol
