### ISSUE TITLE
artifactory doesn't exist

### ISSUE THREAD

**Issue by davidzl** [fynnfluegge/oreon-engine#68]
I get the following exception when building examples.

Downloading from central: https://repo.maven.apache.org/maven2/org/oreon/core/oe-core/3.0.0/oe-core-3.0.0.pom
[WARNING] The POM for org.oreon.core:oe-core:jar:3.0.0 is missing, no dependency information available
[WARNING] The POM for org.oreon.core:oe-gl-api:jar:3.0.0 is missing, no dependency information available
[WARNING] The POM for org.oreon.gl:oe-gl-components:jar:3.0.0 is missing, no dependency information available
[WARNING] The POM for org.oreon.gl:oe-gl-deferred:jar:3.0.0 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.315 s
[INFO] Finished at: 2019-10-14T11:07:02+08:00
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "artifactory" could not be activated because it does not exist.
[ERROR] Failed to execute goal on project examples-opengl: Could not resolve dependencies for project org.oreon.examples:examples-opengl:jar:3.0.0: The following artifacts could not be resolved: org.oreon.core:oe-core:jar:3.0.0, org.oreon.core:oe-gl-api:jar:3.0.0, org.oreon.gl:oe-gl-components:jar:3.0.0, org.oreon.gl:oe-gl-deferred:jar:3.0.0: Failure to find org.oreon.core:oe-core:jar:3.0.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

**Comment by fynnfluegge** [comment]
you need to build parent project (oreon-engine)
