### ISSUE TITLE
Caching Quadtree nodes

### ISSUE THREAD

**Issue by gviznyuk** [fynnfluegge/oreon-engine#69]
Any suggestions on how to cache the quadtree nodes. I've noticed you created the cacheChildrenTree() method, but its not used anywhere.  Was caching the nodes to a hashMap not optimal?

**Comment by fynnfluegge** [comment]
Yes I planned to chache them but not yet implemented. However, this should be trivial with a hashmap (key = location + lod depth). Further I want to create all quadtree nodes in advance and put them all into the cache
