### ISSUE TITLE
Problem with shaders

### ISSUE THREAD

**Issue by Felicitas12** [fynnfluegge/oreon-engine#93]
deferred.DeferredLightingShader 0(43) : error C7636: format layout qualifier not allowed on image parameter

**Comment by Felicitas12** [comment]
Crashing on start, and write error C7636

**Comment by fynnfluegge** [comment]
Hey @Felicitas12, what kind of gpu do you have?

**Comment by Felicitas12** [comment]
> Hey @Felicitas12, what kind of gpu do you have?

rtx 2070

**Comment by fynnfluegge** [comment]
@Felicitas12 unfortunately, I am not able to reproduce the error with RTX 2070. You can create an issue and mention your machine OS and GPU driver version and optionally raise a PR with a fix if you like!
