### ISSUE TITLE
Low fps

### ISSUE THREAD

**Issue by Felicitas12** [fynnfluegge/oreon-engine#94]
![image](https://user-images.githubusercontent.com/83925624/216123411-bf3c21b3-0fca-4cbd-abb2-5a918a55cbfb.png)
30 fps with rtx 2070 on medium settigns, is it good? 
![image](https://user-images.githubusercontent.com/83925624/216123691-1ca86541-77e6-405e-9c0e-171abb4388c2.png)

**Comment by Felicitas12** [comment]
I think empty map with water should give more fps. I saw old video with 2.1 and with gtx 1060 fps was definitely more than 30

**Comment by fynnfluegge** [comment]
You could also reduce the fft resolution of the water in the water-config. 512 or 256 will also generate decent results.

**Comment by fynnfluegge** [comment]
Hm ok, the Opengl FFT seems slow, Vulkan is faster

**Comment by Felicitas12** [comment]
Could you check on your pc, what fps will you have? Because i suppose something wrong with my build. It shouldn't be that low fps.

**Comment by fynnfluegge** [comment]
got also around 30 with your configuration, as I said the Opengl implementation gets slow with high details :/

**Comment by Felicitas12** [comment]
Ah, ok. Thank you)
